### ISSUE TITLE
build/install.sh broken path

### ISSUE THREAD

**Issue by JamesHastings** [alertlogic/ci_lambda_checks#1]
The instructions to install show cloning the "lamba" repository into a local folder called "ci_lambda_checks".  When you go to run the build/install.sh script it is looking for "ci_lamba_checks" instead of "ci_lambda_checks".  This causes Lambda to not be found.  I fixed the code on my local copy to look for "ci_lambda_checks" and installation went smoothly.

**Comment by BarrySkidmore** [comment]
Corrected in 58ed8ac184cf3ee013d40a9ad189d387c62204d0.
