### ISSUE TITLE
Supported AWS Regions table has links to outdated CF file

### ISSUE THREAD

**Issue by edy-chan** [alertlogic/ci_lambda_checks#30]
The s3 link to cloudformation template under [Supported AWS Regions](https://github.com/alertlogic/ci_lambda_checks#supported-aws-regions) section are pointing to outdated template file. In the file the run time environment for the lambda functions are still NodeJS 4.3

example: https://s3-eu-west-1.amazonaws.com/alertlogic-public-repo.eu-west-1/templates/ci_lambda_checks.template

**Comment by ptrakhtman** [comment]
@edy-chan this has been addressed.
